[package]
name = "fractal_maker"
version = "0.5.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
# GUI framework for desktop apps
eframe = "0.27"
# For image saving
image = { version = "0.25", features = ["png"] }
serde = "1.0.219"
serde_json = "1.0.143"
